# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailact', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pcost',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
