# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailact', '0003_auto_20180905_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('prodid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='emailact.Product')),
                ('tot_qty', models.IntegerField()),
                ('last_update', models.DateField()),
                ('next_update', models.DateField()),
            ],
        ),
    ]
