# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-05 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailact', '0004_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('pid', models.IntegerField()),
                ('units', models.IntegerField()),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tunitprice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
